#!/usr/bin/env python3
"""Generate the Unicode property tables felis reads from the UCD.

Usage: gen_tables.py UCD_DIR

UCD_DIR is an unpacked UCD.zip; the dev shell exports the pinned one as
FELIS_UCD_DIR.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def parse(path, prop):
    ranges = []
    for line in path.read_text(encoding="utf-8").splitlines():
        data = line.split("#", 1)[0].strip()
        if not data:
            continue
        cps, value = (field.strip() for field in data.split(";"))
        if value != prop:
            continue
        lo, _, hi = cps.partition("..")
        ranges.append((int(lo, 16), int(hi or lo, 16)))
    ranges.sort()
    merged = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(hi, merged[-1][1]))
        else:
            merged.append((lo, hi))
    return merged


def version(ucd):
    header = (ucd / "auxiliary" / "GraphemeBreakProperty.txt").read_text(
        encoding="utf-8"
    )
    match = re.match(r"# GraphemeBreakProperty-(\d+\.\d+\.\d+)\.txt", header)
    if not match:
        sys.exit(
            "gen_tables: cannot read the UCD version from GraphemeBreakProperty.txt"
        )
    return match.group(1)


def table(name, doc, ranges):
    rows = "".join(f"    ('\\u{{{lo:X}}}', '\\u{{{hi:X}}}'),\n" for lo, hi in ranges)
    return (
        f"/// {doc}\n"
        "#[rustfmt::skip]\n"
        f"pub(super) const {name}: &[(char, char)] = &[\n{rows}];\n"
    )


def module(unicode, source, tables):
    header = (
        f"// @generated by tools/unicode/gen_tables.py from Unicode {unicode}\n"
        f"// {source}; edit the generator, not this file (`just unicode-tables`).\n"
    )
    major, minor, patch = unicode.split(".")
    version_const = (
        "\n/// The UCD version these tables come from.\n"
        "#[cfg(test)]\n"
        f"pub(super) const UNICODE_VERSION: (u8, u8, u8) = ({major}, {minor}, {patch});\n"
    )
    return header + version_const + "".join("\n" + t for t in tables)


def outputs(ucd):
    unicode = version(ucd)
    emoji = ucd / "emoji" / "emoji-data.txt"
    gcb = ucd / "auxiliary" / "GraphemeBreakProperty.txt"
    return {
        REPO / "crates/felis-grid/src/uax29/tables.rs": module(
            unicode,
            "emoji-data.txt and GraphemeBreakProperty.txt",
            [
                table(
                    "EXTENDED_PICTOGRAPHIC",
                    "`Extended_Pictographic` from `emoji-data.txt`.",
                    parse(emoji, "Extended_Pictographic"),
                ),
                table(
                    "EXTEND",
                    "`Grapheme_Cluster_Break=Extend` from `GraphemeBreakProperty.txt`.",
                    parse(gcb, "Extend"),
                ),
            ],
        ),
        REPO / "crates/felis-shaping/src/presentation/tables.rs": module(
            unicode,
            "emoji-data.txt",
            [
                table(
                    "EMOJI_PRESENTATION",
                    "`Emoji_Presentation` from `emoji-data.txt`.",
                    parse(emoji, "Emoji_Presentation"),
                ),
            ],
        ),
    }


def main(argv):
    if len(argv) != 1:
        sys.exit(__doc__.strip())
    for path, text in outputs(Path(argv[0])).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main(sys.argv[1:])
